version: '3'
services:

    mysql:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${mysql_pw}
        volumes:
            - mysql-data:/var/lib/mysql
        command: ["mysqld", "--innodb-buffer-pool-size=512M", "--key-buffer-size=64M", "--query-cache-size=64M", "--tmp-table-size=32M", "--sort-buffer-size=2M", "--query-cache-type=ON"]
        restart: always

    portainer:
        image: portainer/portainer
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer:/data
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql
        restart: always

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
        ports:
            - "9200:9200"
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        restart: always

volumes:
    mysql-data:
    portainer:
    esdata:
